[package]
name = "upki"
version = "1.0.0-beta.3" # Sync with `dist-packages/libupki/dist.toml`
rust-version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true
description = "Platform-independent browser-grade certificate infrastructure"

[features]
default = []
capi = []
fetch = ["reqwest/default-tls", "__fetch"]
fetch-native-tls = ["reqwest/native-tls", "__fetch"]
__fetch = ["dep:reqwest", "dep:serde_json", "dep:tempfile"]

[dependencies]
base64.workspace = true
chrono.workspace = true
clubcard-crlite.workspace = true
directories.workspace = true
hex.workspace = true
reqwest = { workspace = true, optional = true }
rustls-pki-types.workspace = true
rustls-webpki.workspace = true
serde.workspace = true
serde_json = { workspace = true, optional = true }
tempfile = { workspace = true, optional = true }
toml.workspace = true
tracing.workspace = true

[dev-dependencies]
cbindgen.workspace = true
clubcard.workspace = true
clubcard-crlite = { workspace = true, features = ["builder"] }
similar-asserts.workspace = true
tempfile.workspace = true

[lints]
workspace = true

[package.metadata.capi.header]
generation = false

[package.metadata.capi.install.include]
asset = [{ from = "upki.h" }]
