name: build

permissions:
  contents: read

on:
  push:
    branches: ["main", "rel-*", "ci/*"]
    tags:
      - "**"
  pull_request:
  merge_group:
  schedule:
    - cron: "0 18 * * *"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
          - ubuntu-24.04-arm
        rustc:
          - stable
        include:
          - os: ubuntu-latest
            rustc: nightly
        exclude: # and never use macos/windows for merge checks
          - os: ${{ github.event_name == 'merge_group' && 'windows-latest' }}
          - os: ${{ github.event_name == 'merge_group' && 'macos-latest' }}

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v7
        with:
          submodules: true
          persist-credentials: false

      - name: Install ${{ matrix.rustc }} toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rustc }}

      - name: Install cargo-c
        uses: taiki-e/cache-cargo-install-action@v3.0.7
        with:
          tool: cargo-c

      - name: Check all targets
        if: matrix.os != 'windows-latest'
        run: cargo check --locked --all-features --all-targets
      - name: Check all targets (Windows) # Skip upki-openssl on Windows because it requires OpenSSL to be installed
        if: matrix.os == 'windows-latest'
        run: cargo check --locked -p upki -p rustls-upki -p upki-cli -p upki-mirror -p revoke-test --all-features --all-targets
      - name: Run tests (debug)
        if: matrix.os != 'windows-latest'
        run: cargo test --locked -p upki -p rustls-upki -p upki-cli -p upki-mirror -p revoke-test
      - name: Run tests (debug, Windows) # Skip upki-openssl on Windows because it requires OpenSSL to be installed
        if: matrix.os == 'windows-latest'
        run: cargo test -p revoke-test -p rustls-upki -p upki
      - name: Without features
        run: cargo check --locked -p upki --no-default-features
      - name: CLI without features
        run: cargo check --locked -p upki-cli --no-default-features
      - name: CLI with native-tls
        run: cargo check --locked -p upki-cli --no-default-features --features fetch-native-tls

      - name: Build FFI
        run: cargo cbuild --locked -p upki
      - name: Build OpenSSL integration
        if: runner.os != 'Windows'
        run: cargo cbuild --locked -p upki-openssl

      - name: Run system tests (release)
        run: cargo test --locked --release --test system_tests -- --ignored --nocapture

  ffi-example:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
        with:
          submodules: true
          persist-credentials: false

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable

      - name: Install cargo-c
        uses: taiki-e/cache-cargo-install-action@v3.0.7
        with:
          tool: cargo-c

      - name: Check upki/ffi-example builds
        run: |
            mkdir -p dist/ffi
            cargo cinstall -p upki --release --prefix=$(realpath dist/ffi)
            export PKG_CONFIG_PATH=$(realpath dist/ffi/lib/x86_64-linux-gnu/pkgconfig/)

            cd upki/ffi-example
            make
            ./upki-demo || true
            valgrind ./upki-demo || true

  msrv:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          submodules: true
          persist-credentials: false

      - name: Install MSRV toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: "1.85"

      - name: Check MSRV
        run: cargo check --locked --all-features -p upki -p rustls-upki -p upki-openssl -p upki-cli
